Group9-2-itsc3155TermProject-master 3/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # get 'drinks/index'
  
  get 'drinks/search', to: 'drinks#search', as: :search
  # get 'drinks/search/results' => 'drinks#results'

  
  resources :drinks, :liquors, :mixers, :drinkliquors, :drinkmixers
  
  root 'welcome#index'
  
  # root :to => 'drinks#index'
  # root :to => 'drinks#search'


end

Group9-2-itsc3155TermProject-master 3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Group9-2-itsc3155TermProject-master 3/app/models/drink.rb
class Drink < ApplicationRecord
    has_many :drink_liquors, dependent: :destroy
    has_many :liquors, through: :drink_liquors
    has_many :drink_mixers, dependent: :destroy
    has_many :mixers, through: :drink_mixers
    
    enum flavor: { Frozen: 0, Fruity: 1, Hot: 2, Savory: 3, Sour: 4, Spicy: 5, Sweet: 6 }

    
    validates :name, presence: true, length: { minimum: 3 }
    validates :alcoholPerVolume, presence: true, numericality: { greater_than_or_equal_to: 0.00, less_than_or_equal_to: 100.00}
    
    def liquor_names
        DrinkLiquor.where(drink_id: self.id).collect {
            |dl| Liquor.find(dl.liquor_id).name
        }
    end
    
    def mixer_names
        DrinkMixer.where(drink_id: self.id).collect { 
            |dm| Mixer.find(dm.mixer_id).name
        }
    end
    
    def self.search(name, liquors, mixers, flavor)
        if name
            drink = Drink.find_by(name: name)
            if drink
                drinksScored = { drink => 9999 }
                search_match(liquors, mixers, flavor, drinksScored)
                
            else
                search_match(liquors, mixers, flavor)
            end
            
        else
            search_match(liquors, mixers, flavor)
        end
    end
    
    private
        def self.search_match(liquors, mixers, flavor, drinksScored=nil)
            if liquors then liquors = liquors[:Liquor_ids] else liquors = nil end
            if mixers then mixers = mixers[:Mixer_ids] else mixers = nil end
            
            if liquors or mixers or flavor
                if drinksScored then drinksScored = drinksScored else drinksScored = {} end
                    
                if not liquors.empty?
                    liquors[1..-1].each do |liquor|
                        add_result(DrinkLiquor.where(liquor_id: liquor), drinksScored)
                    end
                end
                
                if not mixers.empty?
                    mixers[1..-1].each do |mixer|
                        add_result(DrinkMixer.where(mixer_id: mixer), drinksScored)
                    end
                end
                
                if not flavor.empty?
                    drinks = Drink.where(flavor: flavor)
                    if not drinks.empty?
                        drinks.to_a.each do |drink|
                            if drinksScored[drink] 
                                drinksScored[drink] += 1 
                            else 
                                drinksScored[drink] = 1 
                            end
                        end
                    end
                end
                
                drinksScored.sort_by { |k, v| v }.collect(&:first).reverse
                
            elsif drinksScored
                drinksScored.keys[0]
                
            else
                Drink.all
                
            end
        end
        
        def self.add_result(ingreds, drinksScored)
            if not ingreds.empty?
                ingreds.to_a.each do |ingred|
                    drink = Drink.find(ingred.drink_id)
                    if drinksScored[drink] 
                        drinksScored[drink] += 1 
                    else 
                        drinksScored[drink] = 1 
                    end
                end
            end
        end
end

Group9-2-itsc3155TermProject-master 3/app/models/drink_liquor.rb
class DrinkLiquor < ApplicationRecord
  belongs_to :drink
  belongs_to :liquor
  
  validates :drink, presence: true
  validates :liquor, presence: true
end

Group9-2-itsc3155TermProject-master 3/app/models/drink_mixer.rb
class DrinkMixer < ApplicationRecord
  belongs_to :drink
  belongs_to :mixer
  
  validates :drink, presence: true
  validates :mixer, presence: true
end

Group9-2-itsc3155TermProject-master 3/app/models/liquor.rb
class Liquor < ApplicationRecord
    has_many :drink_liquors
    has_many :drinks, through: :drink_liquors
end

Group9-2-itsc3155TermProject-master 3/app/models/mixer.rb
class Mixer < ApplicationRecord
    has_many :drink_mixers
    has_many :drinks, through: :drink_mixers
end

Group9-2-itsc3155TermProject-master 3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Group9-2-itsc3155TermProject-master 3/app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
    
    def index
    end
    
    def new
        @drink = Drink.new
    end
  

    def show
        @drink = Drink.find(params[:id])
    end
    
    def create
        @drink = Drink.new(drink_params)

        if @drink.save
            render '_success'
        else
            render 'new'
        end
    end
    
    def search
        @drinks = Drink.search(params[:name], params[:liquor], 
                               params[:mixer], params[:flavor])
    end
    
    def edit
        @drink = Drink.find(params[:id])
    end
    
    def update
        @drink = Drink.find(params[:id])
        
        if @drink.update(drink_params)
        else
            render 'edit'
        end
    end    
    
    def destroy
        @drink = Drink.find(params[:id])
        @drink.destroy
        
        redirect_to drinks_path
    end

    
    private 
        def drink_params
            params.require(:drink).permit(:name, :alcoholPerVolume, :flavor, 
            :description, liquor_ids: [], mixer_ids: [])
        end
end

Group9-2-itsc3155TermProject-master 3/app/controllers/drinks_liquors_controller.rb
class DrinksLiquors < ApplicationController
    def create
        @drink = Drink.find(params[:drink_id])
        @drinks_liquors = @drink.drinks_liquors.create(drinks_liquors_params)
        redirect_to drink_path(@drink)
    end
    
        def destroy
        @drink = Drink.find(params[:drink_id])
        @drinks_liquors = @drink.drinks_liquors.find(params[:id])
        @drinks_liquors.destroy
        redirect_to article_path(@drink)
        end

    private
      def drinks_liquors_params
            params.require(:liquors).permit(:name, :unit)
      end
end

Group9-2-itsc3155TermProject-master 3/app/controllers/drinks_mixers_controller.rb
class DrinksMixers < ApplicationController
    def create
        @drink = Drink.find(params[:drink_id])
        @mixer = @drink.drinks_mixers.create(drinks_mixers_params)
        redirect_to drink_path(@drink)
    end
    
        def destroy
        @drink = Drink.find(params[:drink_id])
        @drinks_mixers = @drink.drinks_mixers.find(params[:id])
        @drinks_mixers.destroy
        redirect_to article_path(@drink)
    end

    private
      def drinks_mixers_params
            params.require(:mixers).permit(:name, :unit)
      end
end

Group9-2-itsc3155TermProject-master 3/app/controllers/result_controller.rb
class ResultController < ApplicationController
end

Group9-2-itsc3155TermProject-master 3/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Group9-2-itsc3155TermProject-master 3/app/helpers/application_helper.rb
module ApplicationHelper
    
    def drink_options
  [ ["key", 'value'], ["key2", 'value2'] ]
end

    def liquor_options
 [ ["key", 'value'], ["key2", 'value2'] ]end

    def mixer_options
 [ ["key", 'value'], ["key2", 'value2'] ]end
end

Group9-2-itsc3155TermProject-master 3/app/helpers/drinks_helper.rb
module DrinksHelper
end

Group9-2-itsc3155TermProject-master 3/app/helpers/result_helper.rb
module ResultHelper
end

Group9-2-itsc3155TermProject-master 3/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Group9-2-itsc3155TermProject-master 3/app/views/drinks/_drink_dropdowns.html.erb
<section class="flavors">
   <div class="new_text">Flavor:</div>
   <%= f.select :flavor, Drink.flavors.keys, include_blank: true %> 
</section>

<section class="liquors">
  <div class="new_text">Liquor:</div> 
  <%= f.collection_check_boxes :liquor_ids, Liquor.all, :id, :name do |b| -%>
    <%= b.check_box(class: "checkbox-new") + b.label(class: "checkbox-label-new") { b.text } %>
  <% end %>   
</section>

<section class="mixers">
  <div class="new_text">Mixer:</div>
  <%= f.collection_check_boxes :mixer_ids, Mixer.all, :id, :name do |b| -%>
    <%= b.check_box(class: "checkbox-new") + b.label(class: "checkbox-label-new") { b.text } %>
  <% end %>
</section>

Group9-2-itsc3155TermProject-master 3/app/views/drinks/_header.html.erb
<div id="navContainer">
    <ul id="nav">
        <li> <%= link_to "Home", drinks_path,  class: "button_to", :method => "get" %> </li>
        <li> <%= link_to "Search", search_path, class: "button_to", :method => "get" %> </li>
    </ul>
</div>

Group9-2-itsc3155TermProject-master 3/app/views/drinks/_new_form.html.erb
<%= form_for @drink do |f| %>
 

   <section class="image3"></section>
 <div class="new_box">
    <% if @drink.errors.any? %>
      <div class="error_explanation">
        <h2>
          <%= pluralize(@drink.errors.count, "error") %> prohibited
          this drink from being saved:
        </h2>
        <section class="error_outputs">
          <% @drink.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </section>
      </div>
      <br>
    <% end %>
  <section class="drink_name">
    <div class="new_text">Drink Name:</div> 
    <%= f.text_field :name , placeholder: "Name of new drink..." %>
  </section>
 
  <section class="alcoholPerVolumeRegion">
    <div class="new_text">APV:</div>
    <%= f.number_field :alcoholPerVolume, class: :text_field, step: 0.01, min: 0.00, max: 100.00, placeholder: "APV percent..."%>
  </section>
 
 <%= render 'drink_dropdowns', f: f %>
 
  <section class="descriptionregion">
    <%= f.text_area :description, placeholder: "Description of new drink..." %>
  </section>
 </div>
   <section class="new_submit">
    <%= f.submit %>
  </section>

<% end %>

Group9-2-itsc3155TermProject-master 3/app/views/drinks/_search_forms.html.erb
<%= form_tag(search_path.split('?').first, method: :get) do %>
  <section class="image2"></section>
<div class="box2">

  <section class="drink_name">
    <%= text_field_tag :name, params[:name], placeholder: "Search by drink name..." %>    
  </section>
  <br>
  
  <div class="box3">
    <strong><%= label_tag "liquorName", "Liquor" %><br></strong>
    <section class="liquor_name">
      <%= collection_check_boxes :liquor, :Liquor_ids, Liquor.all, :id, :name, boolean_style: :inline do |b| %>
        <%= b.check_box(class: "checkbox-search") + b.label(class: "checkbox-label") { b.text } %>
      <% end %>
    </section>
    <br>
  </div>
  <div class="box3">
    <strong><%= label_tag "mixerName", "Mixer" %><br></strong>
    <section class="mixer_name">
    <%= collection_check_boxes :mixer, :Mixer_ids, Mixer.all, :id, :name, boolean_style: :inline do |b| %>
      <%= b.check_box(class: "checkbox-search") + b.label(class: "checkbox-label") { b.text } %>
    <% end %>
    </section>
    <br>
  </div>
  <div class="box3">
    <section class="drink_flavor">
      <strong><%= label_tag "drinkFlavor", "Flavor" %><br></strong>
      <%= select_tag :flavor, options_for_select(Drink.flavors), include_blank: true %>
    </section>
  </div>

</div>
  <div class="search_submit">
    <%= submit_tag "Search", class: "btn btn-default" %> 
  </div>
<div class="box2_transparent"></div>

<div class="padding"></div>

<% end %>

Group9-2-itsc3155TermProject-master 3/app/views/drinks/_success.html.erb
<html>
    <head>
        <meta http-equiv="refresh" content="3; URL='<%= new_drink_path %>'" />
    </head>
    <body>
        <main>
            <section class="success_page">
                <h1>
                    Drink creation successful! Redirecting in three seconds...<br>
                    <%= link_to "click here to redirect manually", new_drink_path %>
                </h1>
            </section>
        </main>
    </body>
</html>

<%= render './footer' %>

Group9-2-itsc3155TermProject-master 3/app/views/drinks/index.html.erb
<body class="drink_body">
    <main>
        <div class="drink_div">
            <div id="clearfix">
                <section id="PaddingRegionAbove"></section>
                <section class="box", style="z-index: 2", position:"absolute">
                    <h1>WELCOME TO THE DRINK MIXING APP!</h1>
                    <section class="image"></section>
                    
                    <section class="within_home_box">
                        <h2>WHAT IS IT?</h2>
                        
                        <p class="p">This is an application created by The Squad (Group 9-2) of ITSC 3155, 
                        as mentioned in our footer.  You can use this app to quickly find drinks 
                        based on their mixers & liquors, or by a flavor profile, whatever works 
                        for you!
                        </p>
                    
                        <h2>HOW IT WORKS</h2>
                        <p class="p">To get started, simply click the "Search"  button up top! 
                        When in the search section, simply select the search  terms 
                        by clicking the associated checkboxes and hit "submit" to begin the search! 
                        It's that easy!
                        </p>
                        
                    </section>

                </section>
                <section class="box_transparent", style="z-index: 1", position:"absolute"></section>
                <section id="PaddingRegionBelow"></section>
            
            </div>
        </div>
    </main>
</body>

<%= render './footer' %>

Group9-2-itsc3155TermProject-master 3/app/views/drinks/new.html.erb
<main>
    <%= render 'new_form' %>
</main>

<%= render './footer' %>

Group9-2-itsc3155TermProject-master 3/app/views/drinks/results.html.erb
<%= javascript_include_tag "results.js" %>

<div class = "TheBackground" >
<%= render 'header' %>
</div>
<div class="BackgroundThing">
  
</div>
<footer>
    <h4>Please Drink Responsibly</h4>
    <p>ITSC 3155     |      The Squad (Group 9-2)       |       University of North Carolina at Charlotte     |     2018</p>
</footer>

Group9-2-itsc3155TermProject-master 3/app/views/drinks/search.html.erb
<body class="search_body", style="z-index: 2">
    <main >
        <%= render 'search_forms' %>
        <section class="box2_transparency", style="z-index: 1"></section>
        <div class="results">
            <div class="results_border"></div>
            <div class="results_region">
                <H2>RESULTS</H2>
            </div>
            <div class="drinks_returned">
                <% @drinks.each do |drink| %>
                    <section class="drink_result">
                        <section class="drinkname"><%= drink.name %></section>
                        <div class="information_region">
                            <section class="drinkapv"><strong>APV: </strong><%= drink.alcoholPerVolume %>%</section>
                            <section class="drinkflavor"><strong>Flavor: </strong><%= drink.flavor %></section>
                            <section class="drinkliquor">
                                <strong><%= if drink.liquor_names.count > 1 then "Liquors" else "Liquor" end -%>:</strong>
                                <%= drink.liquor_names.join(', ') %>
                            </section>
                            <section class="drinkmixer">
                                <strong><%= if drink.mixer_names.count > 1 then "Mixers" else "Mixer" end -%>:</strong>
                                <%= drink.mixer_names.join(', ') %>
                            </section>
                            <strong class="directions">Directions:</strong>
                            <section class="drinkdescription"><%= drink.description %></section>
                        </div>
                    </section>
                <% end %>
            </div>
        </div>
        <div class="results_transparency"></div>
    </main>
</body>

<%= render './footer' %>

Group9-2-itsc3155TermProject-master 3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Group92Itsc3155termproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= if controller_name == 'drinks' then render 'drinks/header' end %>
    <%= yield %>
    
  </body>
</html>

Group9-2-itsc3155TermProject-master 3/app/views/welcome/index.html.erb
<body class="welcome_body">
    <div class="welcome_div">
        <h4 class="intro">ALCOHOL'S GREAT, BUT IT'S EVEN GREATER WHEN ENJOYED LEGALLY</h1>
        <p class="age_check">are you over 21?</p>
        
        <table class="welcome_table">
            <tr>
                <th class="welcome_button">
                    <%= button_to "    Not yet!    ", 'https://kidshealth.org/en/teens/alcohol.html', class:"welcome_button", :method => "get" %>
                </th>
                <th class="welcome_button">
                    <%= button_to "Heck yeah!", drinks_path, class: "welcome_button", :method => "get" %>

                </th>
            </tr>
        </table>
    </div>
    <div class="padding2"></div>
</body>